version: "3.8"
services:
 app:
  container_name: datarango
  build:
   context: ./
  volumes:
   - ./:/app
   - /app/node_modules
   - /app/.next
  ports:
   - "3010:3010"
  env_file:
   - .env
  restart: always
