import { OPERATIONS, PORTFOLIO, PROCESS, PROCESS2, STACKS, TESTIMONIALS } from "./home"
import { FOOOTER, NAVIGATION } from "./navigation"

export {
  FOOOTER,
  NAVIGATION,
  OPERATIONS,
  PORTFOLIO,
  PROCESS,
  PROCESS2,
  STACKS,
  TESTIMONIALS,
}
