import { OPERATIONS, PORTFOLIO, PROCESS, PROCESS2, STACKS, TESTIMONIALS } from "./home"
import { COMMUNITY, FOOOTER, NAVIGATION } from "./navigation"
import { APPROACH, SECTORS } from "./learn-more"
import { EVENTS } from "./events"

export {
  APPROACH,
  COMMUNITY,
  EVENTS,
  FOOOTER,
  NAVIGATION,
  OPERATIONS,
  PORTFOLIO,
  PROCESS,
  PROCESS2,
  SECTORS,
  STACKS,
  TESTIMONIALS,
}
