import { OPERATIONS, PORTFOLIO, PROCESS, PROCESS2, STACKS, TESTIMONIALS } from "./home"
import { COMMUNITY, FOOOTER, NAVIGATION } from "./navigation"
import { APPROACH, SECTORS } from "./learn-more"
import { POSTS } from "./blog"

export {
  APPROACH,
  COMMUNITY,
  FOOOTER,
  NAVIGATION,
  OPERATIONS,
  PORTFOLIO,
  POSTS,
  PROCESS,
  PROCESS2,
  SECTORS,
  STACKS,
  TESTIMONIALS,
}
